services:
  local-database:
    container_name: superhero-postgres-db
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - ./.data/:/var/lib/posgresql/data/
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

volumes:
  local-database: