services:
  database:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - database:/var/lib/posgresql/data/
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database: